update README and first publish on npm

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -30,6 +30,16 @@ npm run check-types ||
 # If everything passes... Now we can commit
 echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'
 
+npm run build-storybook ||
+(
+    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
+            Next build failed: View the errors above to see why.
+    '
+    false;
+)
+
+echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
+
 npm run build ||
 (
     echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
@@ -40,7 +50,7 @@ npm run build ||
 
 echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
 
-npm run build-storybook ||
+npm run publish ||
 (
     echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
             Next build failed: View the errors above to see why.
@@ -48,6 +58,5 @@ npm run build-storybook ||
     false;
 )
 
-# If everything passes... Now we can commit
 echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
 
